return {
  cmd = { "diagnostic-languageserver", "--stdio" },
  filetypes = {
    "javascript",
    "javascriptreact",
    "json",
    "typescript",
    "typescriptreact",
    "css",
    "less",
    "scss",
    "markdown",
    "vue",
    "astro",
    "mdx",
    "yaml",
    "txt",
  },
  root_markers = { ".git", "package.json" },
  init_options = {
    formatters = {
      prettier = {
        command = "prettier",
        rootPatterns = { "package.json" },
        args = { "--stdin-filepath", "%filename" },
      },
    },
    formatFiletypes = {
      css = "prettier",
      javascript = "prettier",
      javascriptreact = "prettier",
      json = "prettier",
      scss = "prettier",
      less = "prettier",
      typescript = "prettier",
      typescriptreact = "prettier",
      astro = "prettier",
      vue = "prettier",
      markdown = "prettier",
      mdx = "prettier",
      yaml = "prettier",
    },
  },
}
