cask_args appdir: "/Applications"

# Taps
tap "arkweid/lefthook"
tap "eugenmayer/dockersync"
tap "github/gh"
tap "hashicorp/tap"
tap "heroku/brew"
tap "jesseduffield/lazygit"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
tap "sanemat/font"
tap "suzuki-shunsuke/ghalint"
tap "yutomizutani/jc"

# CLI Tools & Development Dependencies
brew "act"
brew "actionlint"
brew "autoconf"
brew "aws-vault"
brew "awscli"
brew "awsume"
brew "bat"
brew "cairo"
brew "codex"
brew "coreutils"
brew "deno"
brew "devcontainer"
brew "direnv"
brew "fd"
brew "fzf"
brew "gdk-pixbuf"
brew "gh"
brew "ghq"
brew "git", link: true, conflicts_with: ["git"]
brew "git-lfs"
brew "glib"
brew "gnupg"
brew "gobject-introspection"
brew "graphviz"
brew "harfbuzz"
brew "imagemagick"
brew "imath"
brew "jq"
brew "lazygit"
brew "libffi"
brew "libtool"
brew "libxml2"
brew "lua-language-server"
brew "luajit", args: ["HEAD"]
brew "luarocks"
brew "mas"
brew "mise"
brew "neofetch"
brew "neovim"
brew "nghttp2"
brew "ninja"
brew "npm"
brew "pango"
brew "pngpaste"
brew "pnpm"
brew "postgresql", restart_service: true
brew "protobuf"
brew "python@3.9"
brew "reattach-to-user-namespace"
brew "readline", link: true
brew "ripgrep"
brew "rustup-init"
brew "sheldon"
brew "starship"
brew "terraform"
brew "tmux"
brew "tree"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "universal-ctags"
brew "vim"
brew "xz"
brew "yamllint"
brew "yarn"

if OS.mac?
  # Applications
  cask "alacritty"
  cask "chromedriver"
  cask "claude-code"
  cask "cursor"
  cask "deepl"
  cask "devpod"
  cask "discord"
  cask "docker-desktop"
  cask "firefox"
  cask "font-jetbrains-mono-nerd-font"
  cask "ghostty"
  cask "google-chrome"
  cask "google-japanese-ime"
  cask "gyazo"
  cask "imageoptim"
  cask "iterm2"
  cask "muzzle"
  cask "raycast"
  cask "sequel-ace"
  cask "slack"
  cask "spotify"
  cask "visual-studio-code"
  cask "zoom"

  # Mac App Store Applications
  mas "LINE", id: 539883307
  mas "RunCat", id: 1429033973
  mas "Xcode", id: 497799835
end
