# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins.zsh-defer]
github = 'romkatv/zsh-defer'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'
apply = ['fpath']

[plugins.compinit]
inline = 'autoload -Uz compinit && compinit -C'

[plugins.colors]
inline = 'autoload -Uz colors && colors'

[plugins.zeno]
github = 'yuki-yano/zeno.zsh'

[plugins.zeno-bindings]
inline = '''
export ZENO_HOME="$HOME/.config/zeno"
export ZENO_ENABLE_SOCK=1
export ZENO_COMPLETION_FALLBACK=expand-or-complete

function zeno-ghq-cd-post-hook-impl() {
  local dir="$ZENO_GHQ_CD_DIR"
  if [[ -n $TMUX ]]; then
    local repository=${dir:t}
    local session=${repository//./-}
    tmux rename-session "${session}"
  fi
}

zle -N zeno-ghq-cd-post-hook zeno-ghq-cd-post-hook-impl
if [[ -n $ZENO_LOADED ]]; then
  bindkey ' '  zeno-auto-snippet
  bindkey '^m' zeno-auto-snippet-and-accept-line
  bindkey '^i' zeno-completion
  bindkey '^y' zeno-insert-snippet
  bindkey '^x '  zeno-insert-space
  bindkey '^x^m' accept-line
  bindkey '^x^z' zeno-toggle-auto-snippet
  bindkey '^xp' zeno-preprompt
  bindkey '^xs' zeno-preprompt-snippet
  bindkey '^r' zeno-history-selection
fi
'''
# -----------------------

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'
apply = ['defer']

[plugins.dotfiles-sync]
local = '~/.zsh'
use = ['*.zsh']
apply = ['source']

[plugins.zsh-syntax-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'
apply = ['source']

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
