notify = ["/Users/reona5/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[projects."/Users/reona5/src/github.com/reona5/dotfiles"]
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-06-30T05:42:43Z"
source_type = "local"
source = "/Users/reona5/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.hiroppy]
last_updated = "2026-06-12T04:56:04Z"
source_type = "local"
source = "/Users/reona5/.tmux/plugins/tmux-agent-sidebar"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-24T05:17:52Z"
source_type = "local"
source = "/Users/reona5/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[features]
codex_hooks = true
js_repl = false

[mcp_servers.node_repl]
args = []
command = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/reona5/.codex"
CODEX_HOME = "/Users/reona5/.codex"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.623.70822"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "d5cbb8ec1ee520cba7943b1e1accb6b25acd9941ea4e2e9e4dbcf25ff9983a2d"
CODEX_CLI_PATH = "/Applications/Codex.app/Contents/Resources/codex"

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = true
keepRemoteControlAwakeWhilePluggedIn = true
followUpQueueMode = "queue"

[desktop.open-in-target-preferences]
global = "iterm2"

[desktop.open-in-target-preferences.perPath]
"/Users/reona5/src/github.com/reona5/dotfiles" = "iterm2"

[tui]
status_line = ["model-with-reasoning", "current-dir", "context-remaining", "five-hour-limit", "weekly-limit", "codex-version"]
status_line_use_colors = true

[hooks.state]

[hooks.state."/Users/reona5/.codex/hooks.json:post_tool_use:0:0"]
trusted_hash = "sha256:f97d9bbf180a5186984c12f815ad5e4b701ea1aeffd6deef48eba51e7843a8fa"
enabled = true

[hooks.state."/Users/reona5/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:0c190748d9929379531fdcfca3f822ae2b5b6f08d75d93f5e6b273ef27a901c9"

[hooks.state."/Users/reona5/.codex/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:4181e185400e7ab133a68f5680f86a9df6ff48cdd0f43a19aa6409c8a34f793e"

[hooks.state."/Users/reona5/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:d890791159fe0d9507cfec80d9a066c1680bf54be418cee645e51d7205813de3"
