import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0011"
key = "Q"
mods = "Control"

[shell]
args = ["-l", "-c", "tmux a -t default || tmux new -s default"]
program = "/bin/zsh"

[window]
startup_mode = "SimpleFullscreen"

[window.padding]
x = 8
y = 4
