command_timeout = 3000

[username]
style_user = "yellow bold"
style_root = "white bold"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
truncation_length = 100
truncate_to_repo = false

[git_branch]
symbol = "🌱 "
style = "bold green"

[aws]
disabled = true

[time]
disabled = false
format = '[🕙 $time]($style) '
time_format = "%T"

[cmd_duration]
min_time = 10_000
show_milliseconds = true
show_notifications = true
format = 'underwent [$duration](bold yellow)'

[git_status]
disabled = true
